[package]
name = "fontinator"
version = "0.1.0"
authors = ["Matt 961 <matt961@protonmail.ch>"]

[dependencies]
hyper = "0.11"
tokio-core = "0.1"
futures = "0.1"
html5ever = "0.21.0"
markup5ever = "0.6.2"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
hyper-tls = "0.1.2"
rand = "*"
